### ISSUE TITLE
Request for Comments: Documentation and translation setup

### ISSUE THREAD

**Issue by janl** [hoodiehq-archive/documentation#27]
**We’d like to have comprehensive documentation for [Hoodie](http://hood.ie)**, including guides, tutorials, auto-generated API docs and the like. The whole shebang.

We also would like to make it possible for contributors to manually translate the original English documentation into all the languages they can think of.

For this, we need a documentation and translation system that roughly has these features (more important points first):
- **It must be easy to contribute to**. We expect the bulk of the documentation, improvements and translations from drive-by contributes. Any step making contributing harder will make us miss out.
- The documentation format **must not be overly complicated**.
- **It should be easy to track the state** of a translation, for both a translating team to see how far they have gone, and for the project maintainers to see the progress.
- **It should be easy to review and approve changes**. Especially for translations, since the core team only speaks a few languages, it is important that we can handle primary translators and translation reviewers. We strive to have top-notch docs and translations and review are an important step
- **It should be easy to publish any current state** of documentation or translations. Ideally, it is even possible to publish drafts, so more people can have a look at the results. Drafts should be prominently marked as such.
- **It would be nice to have a commenting system** like the php.net docs have, where people can add comments without even having to deal with the documentation format at all. Comments then could be turned into tickets for the docs team and closed when incorporated.

---

**Are we asking the right questions?**

**What should we use?**

We’d love to hear about **your experiences** using one or the other and how it could work for us and what the trade-offs are.

We are **open to anything**, including commercial solutions, or hand-hacked GitHub + Markdown scripts :)

**Thanks for all your input! <3**

**Comment by niallobrien** [comment]
Sounds like a project I'd hack on if you guys don't get any suitable recommendations. :)

**Comment by 0x-r4bbit** [comment]
Started collecting inspiration a while ago for the sofa project too, maybe interesting https://github.com/sofa/docs/issues/1

We decided to use Dgeni (http://github.com/angular/dgeni) which is a very flexible tool to generate documentation. Basically it just executes defined processors in a pipe, which let's you generate whatever you want. The downside: the tool is very good documented yet, so it's a bit hard to get up and running, especially when want to build your own packages.

**Comment by annegentle** [comment]
I believe Mozilla Kitsune meets all these requirements, though I don't know the workflow system well. Take a look at https://github.com/mozilla/kitsune/

**Comment by andywenk** [comment]
I just started to integrate the documentation creation process in the swirl project (https://github.com/skunkwerks/swirl/tree/feature/docs). Basically we are using 
- Hugo for HTML file creation from markdown files: http://hugo.spf13.com/overview/introduction
- git as the review tool
- a simple make task to create the docs
- push the created docs via rsync or git checkout + creation with hugo to a server (not implemented yet)

The idea is to handle as many project related stuff with git. We did not integrate L10n yet but this is easy to do: https://github.com/spf13/hugo/tree/master/examples/multilingual . This process is for sure not comparable with tools like pootle or the like but it is plain simple.

Cheers

Andy

**Comment by HipsterBrown** [comment]
I have heard great things about [Assemble](http://assemble.io), a static site generator built with Node.js , Grunt, and Yeoman, as it is used to generate Zurb's Foundation Docs. It is an open-source project, https://github.com/assemble/assemble/, so it can be contributed to and extended to fit your needs. 

Being built with Node feels like a nice fit with Hoodie's stack and experience as well. The creator's are also trying to make a difference in the world through the use of OSS. You can hear more about the inspiration behind the tool on [JavaScript Jabber](http://javascriptjabber.com/098-jsj-assemble-io-with-brian-woodward-and-jon-schlinkert/). I would love to work with this type of tool to generate interactive and informative docs with Hoodie.

**Comment by lovelydinosaur** [comment]
One to consider: [MkDocs](http://mkdocs.org)

**Comment by mindcrash** [comment]
+1 for [Assemble](https://github.com/assemble/assemble). Already used in production by projects such as Zurb Foundation, but also Zurb Ink, H5BP, Effeckt, Less, Topcoat, the Web Experience Toolkit and tons of other projects. Best three features: it's written on top of Node (which we all love, right?), uses Handlebars (with tons of extensions, and extension points to add even more), and is extremely flexible regarding usage (want to define your data in YAML? JSON? Grunt variables? You got it. Just to name something)

**Comment by siebrand** [comment]
My suggestion is not something that's used on GutHub, but to use [MediaWiki](https://www.mediawiki.org) together with the [Translate extension](https://www.mediawiki.org/wiki/Help:Extension:Translate). Aside from online translation, it also supports offline translations and re-import for the die-hard gettext lovers out there. [KDE UserBase Wiki](http://userbase.kde.org) is a great example of a community using it.

**Comment by keimlink** [comment]
I maintain a [multilingual Django tutorial](http://django-marcador.keimlink.de/) and the translations are managed on [Transifex](http://django-marcador.keimlink.de/). It's free for Open Source projects and they have a great browser editor to translate the message catalogs. Transifex makes it very easy for contributers to add or improve translations because they just need their browser to do it. The translations, even if they are not completed, can be fetched from Transifex later by the project maintainers and commited to the repository.

For writing tutorials and documentation I use [Sphinx](http://sphinx-doc.org/) which supports [translating the documentation with gettext](http://sphinx-doc.org/intl.html). Sphinx uses reStruturedText as markup. It can produce a lot of different output formats (HTML, PDF, manpages, epub, …) and is used by many Open Source projects.

If you think reStructuredText is to complicated I would suggest to have a look at @tomchristie `s [MkDocs](http://www.mkdocs.org/) which is using Markdown instead of reStructuredText. MkDocs has no internationalization support yet, but I'm sure that it is possible to use the same approach used by Sphinx to produce message catalogs using gettext.

Why not simply translating the source files (in which markup they might be) you may ask? There are several reasons not to do it:
- Software developers use i18n tools for a long time to translate their software. gettext and other tools are well tested solutions for the translation problem.
- The first translation of the cloned source files might be easy. But try to imagine what happens if only a few parts of the documentation change: You have to find the differences manually and translate them. This can very fast become a long and frustrating work.
- If you use i18n tools together with a platform like Transifex you lower the barrier for translators dramatically because no translator has to know how to use Git or has to install gettext or other i18n tools on their machine.
- i18n tools like gettext allow you to publish partly translated translations because the missing parts will simply use the original (English) texts.

**Comment by mindcrash** [comment]
Seems another great option for writing documentation just popped up: http://raneto.com/.

It's a Node based SSG specifically designed for building documentation sites / knowledgebases. Templates are based on Mustache (which is probably a big plus for Jan given mustache.js ;) ) and Markdown.

**Comment by zoepage** [comment]
closing this issue, as we found a solution. will reopen, if current solution isn't working out.
