### ISSUE TITLE
Installation for Win, Linux, MacOS

### ISSUE THREAD

**Issue by boennemann** [hoodiehq-archive/documentation#32]
- [x] how to install Hoodie including all dependencies for win
- [x] how to install Hoodie including all dependencies for linux
- [x] how to install Hoodie including all dependencies for macos
- [x] include special Hoodie-Wordings (e.g. difference between API / plugins)

**Comment by lenareinhard** [comment]
as far as I see it, we should differentiate to a) make docs easier to maintain, b) not have the same "all in one place and people get confused"-problem we have up to now. Suggestion:
- [x] prerequisites / system requirements / browser compatibilities https://github.com/hoodiehq/documentation/blob/gh-pages/tutorials/system-requirements-browser-compatibilities-prerequisites-before-getting-started-with-hoodie.md
- [ ] actual Hoodie-Installation
- [ ] special Hoodie wordings -> link to + add (if not done yet) to Glossary https://github.com/hoodiehq/documentation/blob/gh-pages/glossary.md

@zoepage? What do you think?

**Comment by zoepage** [comment]
i love the idea @ffffux 

prerequisites:
we should add how to install on MAC OS with brew. How this is done, is described on hood.ie.

actual installation:
+1

special wordings:
+9000

**Comment by lenareinhard** [comment]
Thanks a lot for the feedback, will do!

**Comment by janl** [comment]
@ola brew on mac creates more problems for beginners than it helps.

Our recommendation for Mac OS X should be:
1. install the binary packages of Node.js from nodes.org
2, download the CouchDB App from couchdb.apache.org

If you are an experienced Mac dev, you can opt to install Node and CouchDB via homebrew, but beware:
1. Node.js will install without npm and print extra install instructions at the end that you need to follow to the letter or you will get a broken npm install.
2. CouchDB on brew takes a while to build, especially when you are not on a cutting edge system, just downloading Erlang takes forever, but if you are on an older system, you have to compile Erlang first, which takes about half an hour.

If you are an experienced Node.js dev, you can use nvm to manage your node installs and install CouchDB however you like.

I think we should only document the first version of this, because it works for most people and those who want the other ones already know what to do.

(just my two cents, I’ve worked on all this quite a bit :)

**Comment by boennemann** [comment]
@janl @zoepage nickname confusion complete

**Comment by zoepage** [comment]
@janl good point! wasn't aware of how many problems brew makes. the thought was just to have something to reduce the steps you need to take to install hoodie. :)

s.th. different:
we should add an information for browser support on the installation guide or somewhere else. 
it's nice to know and gets important imo when we add special features like service worker later and the browser support changes. should also think about how we want to handle this later. 
// cc @ffffux

**Comment by lenareinhard** [comment]
@zoepage re:browser support – good point, we should have system requirements and compatibilities somewhere, where we could add this plus link issues like the known Windows bug. (Can add it here, then I'd suggest renaming the "prerequisites" doc to "system requirements, browser compatibilities and prerequisites for installation" or similar)

**Comment by zoepage** [comment]
@ffffux purrrrfect! thank you <3

**Comment by lenareinhard** [comment]
note re: actual installation guide – aligns with #16, which should be included

**Comment by lenareinhard** [comment]
fyi: changed assignee to me

**Comment by zoepage** [comment]
Here just the browser compatibilities are missing and also the link to the how to get started with hoodie tutorial. The rest is reviewed. :)

@gr2m could you please add the browser compatibilities? Would be amazing!

**Comment by gr2m** [comment]
here it is, could you work it in please, I'm drowning a bit right now
- Firefox latest stable (v29)
- Chrome latest stable (v34)
- Desktop Safari latest stable (v7)
- Internet Explorer v10+
- Opera latest stable (v21)
- Android 4.3+
- iOS Safari latest stable (v7.1)

same as [PouchDB's Browser support](http://pouchdb.com/learn.html#browser_support)

**Comment by lenareinhard** [comment]
thanks, @gr2m, added https://github.com/hoodiehq/documentation/blob/gh-pages/tutorials/system-requirements-browser-compatibilities-prerequisites-before-getting-started-with-hoodie.md

**Comment by zoepage** [comment]
Thank you, you 2!!! <3

**Comment by janl** [comment]
the requirements doc looks good to me.

**Comment by lenareinhard** [comment]
imho we can close this issue now
